### ISSUE TITLE
Style and settings are ignored on mobile device

### ISSUE THREAD

**Issue by ghost** [jifola/Scroll-And-Load-For-Elementor#1]
Hi @jifola ,

tested more with the latest version and found another issue.
On the mobile the style and content settings are ignored for the ajax loaded items.

E.g. the Image Ratio, border radius for the image. I also have a strange padding between images and excerpts. 
![image](https://user-images.githubusercontent.com/52812059/82392904-93d1b000-9a77-11ea-9aba-26442d8a4911.png)

**This is the correct style on mobile**

![image](https://user-images.githubusercontent.com/52812059/82393210-5a4d7480-9a78-11ea-83d4-c61fa59a39db.png)

**This is the style of ajax loaded**
Image ratio is not 0.66 instead of 1.0, border radius missing for images, padding between image and excerpt to large...
![image](https://user-images.githubusercontent.com/52812059/82393234-689b9080-9a78-11ea-8b2d-e26527cf1a1a.png)

**Comment by jifola** [comment]
It seems the loaded post image is missing class. The post image loaded is missing the class .elementor-fit-height. This might sound stupid but how did you get rounded corners in the image? :)

**Comment by ghost** [comment]
> 
> 
> It seems the loaded post image is missing class. The post image loaded is missing the class .elementor-fit-height. This might sound stupid but how did you get rounded corners in the image? :)

![image](https://user-images.githubusercontent.com/52812059/82403996-bae9ab00-9a92-11ea-9ca9-53cce71b4e18.png)

**Comment by jifola** [comment]
That was a stupid question :) It seems all other styles but the image settings are loading, and only some of the image styles are missing. I haven't tested enough yet. With Archive Products and Products there doesn't seem to be a problem.

**Comment by jifola** [comment]
It was not as bad as i thought :) It seems the post thumbnail is just missing the class elementor-fit-height. I have found a solution that works, but I am still considering if it is the best one. Thanks again! I will post here when a new version is uploaded.

**Comment by ghost** [comment]
Tq

**Comment by jifola** [comment]
It should work now. And new version is uploaded. Please let me know if you think it is missing any features!? Still calling it version 1. I guess it has to work before you can even call it a version :) Don't really know how that works.

**Comment by ghost** [comment]
I will try it tomorrow. Normally you would start with versions below 1.
0.1, 0.2... etc., until you think it's ready for testing.
When you thinks it's ready you release a beta version to let us test.
Then the first stable version is 1.0.

This is my understanding...

**Comment by jifola** [comment]
But now it also adds the class to masonry, which is not intended. I will have to find another way.

**Comment by jifola** [comment]
I changed image ratio to a user setting. There are too many factors playing in, and too much code for such a small thing. So making it a user setting was easier. I know it is not good with too many settings, but I am trying to balance performance and user friendliness.
