### ISSUE TITLE
Single Post - Next Post

### ISSUE THREAD

**Issue by jifola** [jifola/Scroll-And-Load-For-Elementor#2]
Will be adding this feature.

**Comment by jifola** [comment]
This feature has now been added.

**Comment by joychetry** [comment]
Would have been better if the browser URL also changes on scroll. It matters a lot in SEO.

**Comment by jifola** [comment]
Okay @joychetry I will look into it! Do you think that adding the "Assign Single Post ID" was a bad idea? I could just make #single-post-container the ID that should be used for the section.

**Comment by joychetry** [comment]
No! If I am getting what you are saying then #single-post-container will only pull post contents, we want to pull share buttons, comment section, TOC and everything else from the target container.
Keep it as it is.
