### ISSUE TITLE
Can't make it work for Elementor Pro Single Post

### ISSUE THREAD

**Issue by guiguilyon** [jifola/Scroll-And-Load-For-Elementor#6]
Hi, sorry for my noobishness.

The [instructions ](http://www.scrollandload.com/#elementor-toc__heading-anchor-14)for Assign Single Post ID are a bit confusing to me.

In a Single Post Elementor template,
First I create a section, go to the "advanced" tab of it and add a random CSS ID in the "CSS id" input field. Then I put any post related widgets I want in this section. It think I understand correctly so far.

Then it says `In the input for “Assign Single Post ID” insert ID (E.g. #single-post-container) or class (E.g. .single-post-container).`  (3rd instruction). Is it in the Scroll and Load widget? I guess it is. But you don't say to put it beforehand. I guess it's obvious. But do we have to put it in the previously created section or in a separate one?

What's even more confusing is that afterwards you write `Insert a section on the page and give it ID or class (E.g. widget-container). And insert “Scroll And Load” widgets inside.` 
It seems like we have to add a second Scroll and load widget in the template. 
So the first one in the section containing the single posts related widgets (Post title, post content and so on) with the #single-post-container ID inside , and a second one (with the #widget-container ID) on its own in a separate section (section with the #widget-container ID)? That's what I understand. But it doesn't sem to work for me.

I load a random single post from the posts archive (where the infinite scroll works fine by the way), scroll to the bottom of the single post and nothing happens while I expect to see the next post load underneath. Do I have to add a Post navigation widget in the single post template?

I use custom post type. Does it only work with standard "posts" of Wordpress?

Anyway thanks for this great plugin. And sorry if I missread or missunderstood something in the instructions.
`

**Comment by jifola** [comment]
Hello @guiguilyon, and thanks! I was just working on the single post function. It is not working properly. It is missing styles and scripts, but it seems to work on my testserver now. It should be up sometime tomorrow. I will try to clearify the instructions. I know they are a bit messy :) I will post here as soon as the new version is up.

**Comment by guiguilyon** [comment]
Awesome! Thank you!

**Comment by jifola** [comment]
Hello again @guiguilyon, I may have promised too much. It is working, but it is a bit too slow for my taste. To many checks i think. So please give me a day or so more.

But could you perhaps explain to me how you would normally add a sidebar to a single post?  Is it done in each individual post or in the single post template?

I am still pretty new to Elementor, so I am not really sure how that is usually done. I would like that the plugin could also be applicable to existing sites without having to go through each post and make changes. That could be comprehensive :(

**Comment by guiguilyon** [comment]
Hi! Sorry for answering this late.

There's a sidebar widget in Elementor.
It will show whatever widget your added in the "Appearance/Widgets" settings of WordPress.

I use the Hello theme, which by default doesn't have any widget available (so the "widgets" menu of WordPress is missing). So I just found and installed the plugin "Sidebars for Hello Elementor Theme"
By Amer Ali, to be able to have a sidebar with Hello.

So to answer your question clearly, you add the sidebar in the single post template, not on each individual post, which will apply to every single post which meet the conditions you set for this particular template, as explained here : https://docs.elementor.com/article/311-conditions.

So you could have some posts with the sidebar and others without it (if they were not set in the conditions of the template containing the sidebar).
You could make a unique template even for a single post if you'd want to! 🙂
There's a short tutorial about Elementor sidebars here : https://youtu.be/bJOoeUhwPws
This Youtuber has a whole series about every widgets of Elementor if you need to know more.

Do you think sidebars are gonna be a problem for infinite scroll?

There's no rush for releasing this feature. You do that on your free time. You don't owe people anything. 🙂

**Comment by jifola** [comment]
Sorry I didn't get back to you before now. I had to get away from the screen for a while and there have been other things to do. Thank you very much for your detailed answer. I will have a closer look, and adapt to it if possible.

Finally I got to where I think it is decent. A lot of frustration and hours later I think I got something. I uploaded the new version just minutes ago. #single-post-container is out of the picture. I haven't changed the guide yet but here is somewhat of an illustration:

'<section 1>Single post widgets. No need to give this section ID anymore.'
'<section 2>Widget container ID with the scroll and load widget inside.'
'<section 3>Loading image ID if you want it.'
'<section 4>Load more ID if you are using click.'
'<section 5>No more items/posts ID if you want it.'

I don't see why it shouldn't work with custom post types. It simply relies on the .elementor-location-single class element that the single post template uses as container. Url and title changes on every new load by the way.

It will probably take some time to figure out the sidebar issue, but you have provided me with what I need to know for a good start thanks! I probably shouldn't give you a time frame this time. That didn't work :)

The new version has also been uploaded to the test page http://www.scrollandload.com/uncategorized/hello-world/

**Comment by jifola** [comment]
Off course I just bumped into another issue. I move the plugin elements below the .elementor-location-single class element for conveniency. So now they loose some of their style properties. Which means that if you set your button to align center, that no longer applies ... damn!

**Comment by jifola** [comment]
Last mentioned issue has been solved. And it meant less code. What a pleasant surprise :)

**Comment by guiguilyon** [comment]
Wow ! Thank you! I've been quiet busy these last few days and this matter was at the back of my mind. But I just thought about it and am pleased that you made progress!
Haven't had time to test it yet. But I'll get back to you as soon as I do. I'm pretty excited! 😁

**Comment by guiguilyon** [comment]
Ok! I finally got some time to yet it out and it works! This is great!
That is so nice to see posts appearing add you scroll! 

I have some questions though, but not directly related to this topic. So I guess I should create new topics.

Anyway, thank you very very much for this plugin. This is the only one I know that has these features. I can't understand why it hasn't been done sooner! 😁

**Comment by jifola** [comment]
Thanks! :) But just keep in mind that if you are using Google Analytics to track page traffic I am not sure it tracks more loaded posts. I will have to investigate some more. And Oembed still only applies to the first loaded post so far. If your new topic concerns the image ratio setting, I have removed it from the newest version. It is handled by a script now.
