### ISSUE TITLE
Missing Return Links

### ISSUE THREAD

**Issue by nikt12345** [jifola/Scroll-And-Load-For-Elementor#7]
Hi,

I found your plugin great, it works perfect with my Wordpress theme. I'm just having a SEO issue with "Missing Return Links". This is due to a compatibility problem between Yoast and the Post Pro Elementor widget I'm using. If I set "No pagination" it disappears, but after installing your plugin, probably cause I switched again pagination to "Previous/Next" it appears again.

This is the last reply I received from Yoast Support about this issue:

"Yoast SEO utilizes the built-in WordPress core functions to recognize pagination. The blog page on your site uses an Elementor module to add pagination to the blog page instead of using the WordPress core static blog page. For Yoast SEO to detect pagination on a non-static blog page, a manual page break must be included in the content.

Please reach out to Elementor to request compatibility with our plugin's recognition of pagination. Alternatively, you or your developer can use the wpseo_canonical, wpseo_prev_rel_link, and wpseo_next_rel_link filters to customize these tags. Some example code snippets can be found [here](https://gist.github.com/amboutwe/2aa7dcc9a38986e11fac68c7306cc091) and [here](https://gist.github.com/amboutwe/66c583d2ef4015a8a244ee3e0e8cd1a0)."

**I know it is not your fault and my question is:**

Is there any way to maintain your plugin "active and working" selecting "no pagination"?

Thanks,

Nicholas

**Comment by nikt12345** [comment]
I just realize that the problem is related to the Seo Audit, as with the current setup and the plugin installed the canonical rel in source code seems fine. So, there's no need to check it. Thanks!

**Comment by jifola** [comment]
Okay :)
