### ISSUE TITLE
Masonry fails to update

### ISSUE THREAD

**Issue by Salvatory** [jifola/Scroll-And-Load-For-Elementor#8]
Hiya, when scrolling with 'Masonry' enabled, it fails to resort the cards or align them with the previous ones, it then seems to forget that masonry is enabled and just aligns cards grid style on the lazyloaded content.

**Comment by jifola** [comment]
Hello, maybe I am misunderstanding what you are saying but this seems to work? https://www.scrollandload.com/posts-load-more/

**Comment by Salvatory** [comment]
> Hello, maybe I am misunderstanding what you are saying but this seems to work? https://www.scrollandload.com/posts-load-more/

Here's an example: The cards are different sizes, and when the lazyload adds more cards, they are no longer nested - https://spiralking.com/category/development/

**Comment by jifola** [comment]
Ah okay, loaded items are missing minus margin top. Thanks for letting me know. I will look into it.

**Comment by jifola** [comment]
Hello again @Salvatory. Just to keep you updated. I have a solution. But right now I am trying to figure out how it is best implemented.

**Comment by jifola** [comment]
Hello again again @Salvatory it is almost there :) Masonry is working! I have removed custom selectors and have chosen to focus on Elementor widgets only. I have learned some new things and are applying it to the rest of the plugin. And I am trimming everywhere I can. It will be ready sometime Sunday.

**Comment by Salvatory** [comment]
You are a STAR :)

**Comment by jifola** [comment]
Haha that was a fast reply :)

**Comment by jifola** [comment]
Hey @Salvatory it seems to work now. I have uploaded the new version :)

**Comment by Salvatory** [comment]
Looking awesome! Thanks for your work on this.... I really love lazy loading :)
